# Generated by Django 3.2.7 on 2021-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beerType', models.CharField(max_length=100)),
                ('brewery', models.CharField(max_length=100)),
                ('ibu', models.IntegerField()),
                ('alcoholPercent', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
