# Generated by Django 3.2.7 on 2021-10-20 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='bestBefore',
        ),
        migrations.AddField(
            model_name='locations',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='best before date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='location',
            field=models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West')], default='N', max_length=1),
        ),
    ]
