# Generated by Django 3.2.7 on 2021-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211020_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='date',
            field=models.DateField(verbose_name='best before date'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='location',
            field=models.CharField(choices=[('N', 'North Vancouver BCL'), ('E', 'East Vancouver BCL'), ('S', 'South Vancouver BCL'), ('W', 'West Vancouver BCL')], default='N', max_length=1),
        ),
    ]
