# Generated by Django 3.2.7 on 2021-10-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211020_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='stock'),
            preserve_default=False,
        ),
    ]
