# Generated by Django 3.2.7 on 2021-10-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211020_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='color',
        ),
        migrations.AddField(
            model_name='brew',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.Ingredient'),
        ),
    ]
